"""empty message

Revision ID: dd3d248d0912
Revises: None
Create Date: 2016-09-16 13:07:33.932235

"""

# revision identifiers, used by Alembic.
revision = 'dd3d248d0912'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazev', sa.String(length=128), nullable=False),
    sa.Column('created_ts', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('contact_person', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('website', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazev')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazev', sa.String(length=128), nullable=False),
    sa.Column('created_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazev')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('jmeno', sa.String(length=64), nullable=False),
    sa.Column('prijmeni', sa.String(length=64), nullable=False),
    sa.Column('pw_hash', sa.String(length=500), nullable=False),
    sa.Column('created_ts', sa.DateTime(), nullable=False),
    sa.Column('remote_addr', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('default_idfirm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('g-f_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id', 'group_id', 'firma_id')
    )
    op.create_table('u-f_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'firma_id', 'user_id')
    )
    op.create_table('u-g_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'group_id', 'user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('u-g_association')
    op.drop_table('u-f_association')
    op.drop_table('g-f_association')
    op.drop_table('user')
    op.drop_table('group')
    op.drop_table('firma')
    ### end Alembic commands ###
